# =========================
# BUILD STAGE
# =========================
FROM maven:3.9.16-eclipse-temurin-17 AS build

WORKDIR /app

COPY pom.xml .
COPY src ./src

RUN mvn clean package -DskipTests


# =========================
# RUNTIME STAGE
# =========================
FROM tomcat:9.0-jdk17

RUN rm -rf /usr/local/tomcat/webapps/*

COPY --from=build /app/target/HackHub-1.0-SNAPSHOT.war \
    /usr/local/tomcat/webapps/ROOT.war

COPY start.sh /start.sh

RUN sed -i 's/\r$//' /start.sh
RUN chmod +x /start.sh

EXPOSE 80

CMD ["/bin/sh", "/start.sh"]